### ISSUE TITLE
Prod/Dev/Test Environment configs

### ISSUE THREAD

**Issue by tlorens** [absolute-quantum/DoctrineEncryptBundle#59]
For local dev, it'd be nice to not have the entity properties encrypted.  Right now I have all my attributes commented (using an # vs @) to note which fields I'm going to encrypt later when we're production ready.

**Comment by Zombaya** [comment]
You could always make a class `DummyEncryptor` implementing the `EncryptorInterface`, which simply returns the original string.

```php
namespace App\Example;

use Ambta\DoctrineEncryptBundle\Encryptors\EncryptorInterface;

class DummyEncryptor implements EncryptorInterface
{
    public function encrypt(string $data): string
    {
        return $data;
    }

    public function decrypt(string $data): string
    {
        return $data;
    }
}
```

Now you can override the default service with your custom encryptor in the services-file for the environment you want to change. I will assume `dev` for the example.  Modify `config/services_dev.yaml`

```yaml
# config/services_dev.yaml
services :
  ambta_doctrine_encrypt.encryptor :
    class : App\Example\DummyEncryptor
```

Note: I did not actually test this, but this should get you in the right direction.
