### ISSUE TITLE
Disable encryption regarding to the environment 

### ISSUE THREAD

**Issue by orangevinz** [absolute-quantum/DoctrineEncryptBundle#81]
Except not loading the bundle for `all`, is there any way to disable encryption for specific env?
`Halite` seems to be applied when config is null or unknown

Doing something like that ?

```yaml
ambta_doctrine_encrypt:
    encryptor_class: null
    secret_directory_path: '%kernel.project_dir%'
```
